name: CloudOpsHub CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Verify Docker
        run: docker --version

      - name: Check Python Syntax
        run: |
          python -m compileeall backend
