name: CloudOpsHub CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Verify Docker
        run: docker --version

      - name: Check Python Syntax
        run: |
          python -m compileall backend

      - name: Build Docker Image
        run: |
          docker build \
            -t cloudopshub:test \
            -f docker/backend/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cloudopshub:latest
            ${{ secrets.DOCKER_USERNAME }}/cloudopshub:${{ github.sha }}
